# Generated by Django 2.1.7 on 2020-06-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='total_spots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
    ]
