# Generated by Django 2.1.7 on 2019-08-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190801_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
