# Generated by Django 2.1.7 on 2020-06-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190827_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover',
            field=models.ImageField(null=True, upload_to='company_cover'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='company_logos'),
        ),
    ]
