# Generated by Django 2.1.7 on 2020-06-14 19:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200614_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
