# Generated by Django 2.1.7 on 2020-06-03 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255)),
                ('start_date', models.DateTimeField()),
                ('regime', models.IntegerField(choices=[(2, 'Normal (2h)'), (1, 'Fast-Charge (1h)')], default=2)),
                ('reminder', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('spot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spot', to='parking.Spot', verbose_name='Spot')),
            ],
        ),
    ]
